CURRICULUM = [

    # ── TIER 1 ─────────────────────────────────────────────────────────────
    {"topic": "URL Shortener",                      "tier": 1},
    {"topic": "Rate Limiter",                       "tier": 1},
    {"topic": "News Feed / Timeline",               "tier": 1},
    {"topic": "Notification System",                "tier": 1},
    {"topic": "Chat System",                        "tier": 1},
    {"topic": "Search Autocomplete",                "tier": 1},
    {"topic": "Distributed Cache (Redis)",          "tier": 1},
    {"topic": "Web Crawler",                        "tier": 1},
    {"topic": "YouTube / Video Platform",           "tier": 1},
    {"topic": "Uber / Ride Sharing",                "tier": 1},
    {"topic": "Google Drive / File Storage",        "tier": 1},
    {"topic": "Distributed Message Queue",          "tier": 1},
    {"topic": "Consistent Hashing",                 "tier": 1},
    {"topic": "CAP Theorem",                        "tier": 1},
    {"topic": "Database Sharding",                  "tier": 1},
    {"topic": "CDN Architecture",                   "tier": 1},
    {"topic": "SQL vs NoSQL Tradeoffs",             "tier": 1},
    {"topic": "Load Balancer Design",               "tier": 1},
    {"topic": "Key-Value Store",                    "tier": 1},
    {"topic": "Distributed Job Scheduler",          "tier": 1},
    {"topic": "Distributed Lock Service",           "tier": 1},
    {"topic": "Task Queue System",                  "tier": 1},
    {"topic": "Service Discovery System",           "tier": 1},
    {"topic": "Monitoring & Alerting System",       "tier": 1},
    {"topic": "Push Notification Service",          "tier": 1},
    {"topic": "Flash Sale System",                  "tier": 1},
    {"topic": "Full-Text Search Engine",            "tier": 1},
    {"topic": "Pastebin",                           "tier": 1},

    # ── TIER 2 ─────────────────────────────────────────────────────────────
    {"topic": "Twitter / Social Graph",             "tier": 2},
    {"topic": "Hotel / Ticket Booking System",      "tier": 2},
    {"topic": "Ad Click Aggregation",               "tier": 2},
    {"topic": "Proximity Service / Yelp",           "tier": 2},
    {"topic": "Payment System",                     "tier": 2},
    {"topic": "Collaborative Document Editor",      "tier": 2},
    {"topic": "Ticketmaster / Flash Sale",          "tier": 2},
    {"topic": "Payment Gateway",                    "tier": 2},
    {"topic": "OAuth 2.0 / SSO",                   "tier": 2},
    {"topic": "Typeahead Search",                   "tier": 2},
    {"topic": "Netflix",                            "tier": 2},
    {"topic": "Airbnb",                             "tier": 2},
    {"topic": "Instagram",                          "tier": 2},
    {"topic": "WhatsApp",                           "tier": 2},
    {"topic": "Slack",                              "tier": 2},
    {"topic": "Amazon S3 / Object Storage",         "tier": 2},
    {"topic": "Distributed Tracing System",         "tier": 2},
    {"topic": "API Gateway",                        "tier": 2},
    {"topic": "Event Sourcing & CQRS",              "tier": 2},
    {"topic": "Circuit Breaker Pattern",            "tier": 2},
    {"topic": "Time Series Database",               "tier": 2},
    {"topic": "Content Moderation System",          "tier": 2},
    {"topic": "A/B Testing Platform",               "tier": 2},
    {"topic": "Webhook Delivery System",            "tier": 2},
    {"topic": "Email System (Gmail-scale)",         "tier": 2},
    {"topic": "Dropbox / File Sync",                "tier": 2},
    {"topic": "Discord",                            "tier": 2},
    {"topic": "TikTok",                             "tier": 2},
    {"topic": "End-to-End Encrypted Chat",          "tier": 2},
    {"topic": "Container Orchestration (Kubernetes)","tier": 2},
    {"topic": "Event Streaming Platform (Kafka)",   "tier": 2},
    {"topic": "Data Lake",                          "tier": 2},
    {"topic": "ETL Pipeline",                       "tier": 2},
    {"topic": "Video Transcoding Pipeline",         "tier": 2},

    # ── TIER 3 — ML/AI infra (unlocks after 10 Tier 1 sent) ───────────────
    {"topic": "LLM Serving Infrastructure",         "tier": 3},
    {"topic": "Vector Search Engine",               "tier": 3},
    {"topic": "Feature Store",                      "tier": 3},
    {"topic": "RAG System",                         "tier": 3},
    {"topic": "ML Platform (Michelangelo)",         "tier": 3},
    {"topic": "Recommendation Engine",              "tier": 3},
    {"topic": "ML-based Fraud Detection",           "tier": 3},
    {"topic": "Embeddings Generation Pipeline",     "tier": 3},
    {"topic": "Real-Time ML Inference Service",     "tier": 3},
    {"topic": "Model Monitoring & Drift Detection", "tier": 3},

    # ── TIER 4 — Advanced (unlocks after 20 total sent) ───────────────────
    {"topic": "Google Search",                      "tier": 4},
    {"topic": "Google Maps",                        "tier": 4},
    {"topic": "Distributed File System (HDFS)",     "tier": 4},
    {"topic": "Stream Processing (Kafka+Flink)",    "tier": 4},
    {"topic": "Data Warehouse",                     "tier": 4},
    {"topic": "Code Execution Sandbox",             "tier": 4},
    {"topic": "Fraud Detection System",             "tier": 4},
    {"topic": "Digital Wallet (Venmo/PayPal)",      "tier": 4},
    {"topic": "Stock Trading Platform",             "tier": 4},
    {"topic": "Real-Time Leaderboard",              "tier": 4},
]
